#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

#include <stdint.h>

#define BOARD_DISPLAY_WIDTH       480U
#define BOARD_DISPLAY_HEIGHT      272U
#define BOARD_DISPLAY_BPP         4U
#define BOARD_LVGL_TICK_PERIOD_MS 1U

#define BOARD_SDRAM_BASE_ADDRESS  0xC0000000UL
#define BOARD_SDRAM_SIZE          (8U * 1024U * 1024U)
#define BOARD_FRAMEBUFFER_SIZE    (BOARD_DISPLAY_WIDTH * BOARD_DISPLAY_HEIGHT * BOARD_DISPLAY_BPP)
#define BOARD_FRAMEBUFFER_0_ADDR  BOARD_SDRAM_BASE_ADDRESS
#define BOARD_FRAMEBUFFER_1_ADDR  (BOARD_FRAMEBUFFER_0_ADDR + BOARD_FRAMEBUFFER_SIZE)
#define BOARD_LVGL_HEAP_ADDR      (BOARD_SDRAM_BASE_ADDRESS + 0x00100000UL)
#define BOARD_LVGL_HEAP_SIZE      (512U * 1024U)

#define BOARD_LVGL_DRAW_BUFFER_LINES 40U
#define BOARD_LVGL_DRAW_BUFFER_SIZE  (BOARD_DISPLAY_WIDTH * BOARD_LVGL_DRAW_BUFFER_LINES * BOARD_DISPLAY_BPP)
#define BOARD_LVGL_DRAW_BUFFER_0_ADDR (BOARD_LVGL_HEAP_ADDR + BOARD_LVGL_HEAP_SIZE)
#define BOARD_LVGL_DRAW_BUFFER_1_ADDR (BOARD_LVGL_DRAW_BUFFER_0_ADDR + BOARD_LVGL_DRAW_BUFFER_SIZE)

#define BOARD_DIAGNOSTIC_SDRAM_TEST_ADDR (BOARD_SDRAM_BASE_ADDRESS + 0x007F0000UL)
#define BOARD_DIAGNOSTIC_SDRAM_TEST_SIZE (4U * 1024U)

#define BOARD_AUDIO_SAMPLE_RATE_HZ 48000U
#define BOARD_AUDIO_DEFAULT_VOLUME 70U

#endif
